# Generated by Django 4.2 on 2025-11-13 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('endereco_entrega', models.CharField(max_length=255, verbose_name='Endereço de Entrega')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Pedido')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total Bruto')),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Desconto Aplicado')),
                ('total_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total Final')),
                ('itens_json', models.TextField(default='[]', verbose_name='Itens do Pedido (JSON)')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço Unitário')),
                ('is_combo', models.BooleanField(default=False, verbose_name='É um Combo?')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
