# Generated by Django 4.2 on 2025-11-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='is_combo',
        ),
    ]
